### ISSUE TITLE
sqlite required

### ISSUE THREAD

**Issue by mrcnpdlk** [skipperbent/pecee-pixie#104]
Why in new version sqlite php extension is required?
In my opinion ext-sqlite could be as suggested package defined in `composer.json`

Furthermore: In my php 7.2.9 I don't have the `sqlite` - `sqlite3` instead.

**Comment by skipperbent** [comment]
Hey.

In the exception handler the library uses a constant from sqlite. I was unable to find the exact error code, but it is a little excessive to require that entire extension for that one error-code that's true.

/ Simon

**Comment by mrcnpdlk** [comment]
It is checked in [Sqlite adapter](https://github.com/skipperbent/pecee-pixie/blob/v4-release/src/Pecee/Pixie/ConnectionAdapters/Sqlite.php#L29):
```php
if (\extension_loaded('pdo_sqlite') === false) {
            throw new Exception(sprintf('%s library not loaded', 'pdo_sqlite'));
        }
```

Only if we use this adapter we compare error code with constant `SQLITE_CONSTRAINT`

**Comment by skipperbent** [comment]
Yeah, but it's still a potential error as it's used within the exception handler. So if you use the MySQL adapter it could still end up with checking for a constant which is not present and if the constant is not available in the php installation, it would create a warning.

Best thing would be to find the exact error code or make the exception handler more abstract.

**Comment by mrcnpdlk** [comment]
SQLITE_CONSTRAINT = 19

**Comment by mrcnpdlk** [comment]
`SQLITE_CONSTRAINT` is checked only in one [place](https://github.com/skipperbent/pecee-pixie/blob/v4-release/src/Pecee/Pixie/Exception.php#L103). There is switch-case statement, so only for Sqlite adapter it is checked.

**Comment by skipperbent** [comment]
That's true, you're absolutely right - I'm sorry I didn't notice that it checked the adapter class, guess I acted to quickly on the PhpStorm warning. Iwill revert the change- great with your feedback!

**Comment by mrcnpdlk** [comment]
I've checked one thing....
```php
var_dump(SQLITE_CONSTRAINT);
```
And unfortunately despite of loading sqlite extension in response I have:
```
Use of undefined constant SQLITE_CONSTRAINT - assumed 'SQLITE_CONSTRAINT' (this will throw an Error in a future version of PHP)
```

Do You also have similar problem?

**Comment by skipperbent** [comment]
@mrcnpdlk 

That's weird, I get the exact same error- despite having the extension installed. PhpStorm even knows the constant and even suggest using the extension.

Maybe the custom exceptions for SQLite should be disabled for now, and implemented properly with unit-tests etc. according to their official documentation: https://www.sqlite.org/rescode.html - seems like the current implementation are bugged even with the extension enabled.

What do you think?

/ Simon

**Comment by mrcnpdlk** [comment]
Ver 4.11.0 is working. You can close issue.
