### ISSUE TITLE
IQueryBuilderInterface broke IDE autocomplete feature

### ISSUE THREAD

**Issue by dev-rfc** [skipperbent/pecee-pixie#110]
In Connection class, the getQueryBuilder() method returns a QueryBuilderHandler object, but most QueryBuilderHandler's methods returns IQueryBuilderHandler, which is an empty interface

Connection.php 
```
    public function getQueryBuilder(): **QueryBuilderHandler**
    {
        return new QueryBuilderHandler($this);
    }
```

QueryBuilderHander.php

```
public function table($tables = null): **IQueryBuilderHandler**
{
	if ($tables === null) {
		return $this->from($tables);
	}
	if (\is_array($tables) === false) {
		// Because a single table is converted to an array anyways, this makes sense.
		$tables = \func_get_args();
	}
	return $this->newQuery()->from($tables);
}
```
And IQueryBuilderHandler.php

```
namespace Pecee\Pixie\QueryBuilder;
interface **IQueryBuilderHandler** {
}

```
So the following code cannot autocomplete:

`$connection->getQueryBuilder()->table('my_tbl')-> ??`

I implemented the IQueryBuilderInterface using public methods from the QueryBuilderClass, but there is another problem which involves some breaking changes.

Sometimes QueryBuilderHandler's methods returns QueryBuilderHandler instead of IQueryBuilderHandler:

```
/**
 * Fetch query results as object of specified type
 *
 * @param string $className
 * @param array $constructorArgs
 *
 * @return static
 */
public function asObject(string $className, array $constructorArgs = []): QueryBuilderHandler
{
	return $this->setFetchMode(PDO::FETCH_CLASS, $className, $constructorArgs);
}

/**
 * Add fetch parameters to the PDO-query.
 *
 * @param mixed $parameters ...
 *
 * @return static
 */
public function setFetchMode($parameters = null): IQueryBuilderHandler
{
	$this->fetchParameters = \func_get_args();
	return $this;
}
```

IQueryBuilderHandler sounds like a "marker interface", so those QueryBuilderHandler's methods should return QueryBuilderHandler, not IQueryBuilderHandler. Or do you implement the interface and always return the interface itself (except if asObject() is a specific QueryBuilderHandler's implementation, which doesn't seems to be the case), or you don't use any interface at all. 

Thank you, and good code.

**Comment by mrcnpdlk** [comment]
You're right, but for example my IDE (PHP Storm) works perfect.
It can read also annotated returned type.

**Comment by dev-rfc** [comment]
I tested on Apache NetBeans 9, and doesn't work.

**Comment by dev-rfc** [comment]
Tested on Visual Studio Code, not working too.

![qb](https://user-images.githubusercontent.com/16182725/48641001-90abbe80-e9bf-11e8-9f78-a3d85319aaf5.png)

**Comment by skipperbent** [comment]
Sounds like the IDE is prefering the methods return type over the phpdocs. Php is not that great with types so phpdocs are important, so it's I would consider upgrading your ide.

I've changed the return-type to `self`, which should work however you might experience some oddities if phpdocs aren't parsed properly.

The changes will be available in the upcoming release.
