### ISSUE TITLE
Cannot update value when using a value from another table.

### ISSUE THREAD

**Issue by maciek-d** [skipperbent/pecee-pixie#113]
am trying to update a column from one table based on values from another table however when i ran my query i simply updated the values with a text `table2.values` rather with the actual values.

This is my query:

`$table1 = $query_builder->table('table1');
$table1
       ->leftJoin("table2", "table1.id", "=", "table2.join_id")
       ->whereNotNull("table2.values") 
       ->update(['table1.values' => 'table2.values']);`

**Comment by mrcnpdlk** [comment]
You should use `raw()` method.
**This example will work.**
```php
$qb = $oApp->sqlConn->getQueryBuilder();
$qb
        ->table('dummy')
        ->leftJoin('dummy2', 'dummy.id', '=', 'dummy2.id')
        ->update([
            'dummy.name' => $qb->raw('dummy2.name'),
        ])
    ;
```

Unfortunately aliasing for this example doesn't work. It should be fixed.
```php
        $qb
        ->table(['dummy'=>'a'])
        ->leftJoin(['dummy2','b'], 'a.id', '=', 'b.id')
        ->update([
            'a.name' => $qb->raw('b.name'),
        ])
    ;
```
Output error with raw sql:
```
Unknown column 'a.name' in 'field list'
string(85) "UPDATE `dummy` LEFT JOIN `dummy2` AS `b` ON `a`.`id` = `b`.`id` SET `a`.`name`=b.name"
```
