### ISSUE TITLE
first() method generates PHP Notice

### ISSUE THREAD

**Issue by mrcnpdlk** [skipperbent/pecee-pixie#12]
After upgrade from 3.2.1 to 3.2.2 library genarates PHP Notice during call first() method when result is empty:
`
PHP Notice:  Undefined offset: 0 in [...]/Composer/pecee/pixie/src/Pecee/Pixie/QueryBuilder/QueryBuilderHandler.php on line 226`

After merge, [line](https://github.com/skipperbent/pecee-pixie/blob/3d0a8de1a686c27ea14a2bd02f6b6b221e26b805/src/Pecee/Pixie/QueryBuilder/QueryBuilderHandler.php#L225)
`return empty($result) ? null : $result[0];`
was replaced by:
`return null === $result ? null : $result[0];`

Method get() should return always \stdClass[] (in my opinion is bug in documentation), so empty array should not be checked by equaling to NULL.

**Comment by skipperbent** [comment]
Hi @mrcnpdlk.

I'm sorry to hear that the last update has caused some issues - the notice you are describing will be fixed right away and the old behavior will be restored. The new release will be available shortly.

**Comment by skipperbent** [comment]
The issue has been released in version 3.2.3 - I appreciate you taking the time to report the issue 👍

**Comment by mrcnpdlk** [comment]
I'am preparing now branch with fixed phpdoc blocks.
Are you thinking about forcing php 7 in this library - there is better handling of variables type?

**Comment by skipperbent** [comment]
@mrcnpdlk Great - I'm glad to hear that!

Currently this fork is only created to have a maintainer on the library. The next version will properly be PHP 7 only and a complete remake of the fork to improve simplicity and performance.

/ Simon

**Comment by mrcnpdlk** [comment]
I have just upgraded to 3.2.3. 
The PHP Notice disappeared - i think you can close this issue.
Thanks for help.

**Comment by skipperbent** [comment]
@mrcnpdlk - I'm glad to hear that it solved the issue you were experiencing. Thanks for taking the time to report the issue and using the library.

/ Simon
