### ISSUE TITLE
Using PHPStan for finding errors

### ISSUE THREAD

**Issue by mrcnpdlk** [skipperbent/pecee-pixie#127]
What do You thing about adding support for PhpStan? 
https://github.com/phpstan/phpstan

**Comment by skipperbent** [comment]
What I like about .NET is actually that you have to build. It doesn't correct bad code, but you will instantly see if you've done something that breaks the code. I like the idea of phpstan. Would be nice if this feature was build in in phpstorm! I think it's a great idea! Github actions would be a great addition too, I just can't be bothered with learning the configuration and fiddeling with the setup. Seems soo complicated

**Comment by mrcnpdlk** [comment]
Config of phpstan is quite simple.
I'll prepare the patch.
