### ISSUE TITLE
Transaction in batch insert

### ISSUE THREAD

**Issue by mrcnpdlk** [skipperbent/pecee-pixie#31]
I think, that batch insert should be in transaction.

**Comment by skipperbent** [comment]
Yeah I totally agree - would make sense to do it like that.

Thought about maybe we should also refactor the library so queries is always an object instead of now where it can either be `string`, `\Closure` or `Raw` - which makes our job at setting the return-type miserable - what do you think?

**Comment by mrcnpdlk** [comment]
It is good thought but hard to accomplish.
Do you have any idea how to do this?
Fist of all, the solution have to be user friendly.
We can do this, using different methods depended of arguments, for example:
  - where(string),
  - whereRaw(raw),
  - whereClosure(closure)
Disadvantages - many many methods and code duplicates.

Second, as you said is common Adapter but a think that obfuscate the code and using library will be harder.

**Comment by skipperbent** [comment]
I'm currently changing the insert so it uses your new transaction features 👍  

I'm thinking that the library will behave the same - the object is only used internally.

For instance - when you call where(), the internal where-handler creates a object that contains either the string, \Raw or closure. That way, all other internal method calls inspects that object-type instead of the `Raw`, `\Closure`, `string` combination that we got going on now - which is more confusing. That way, we will also get an code-error if a wrong type is passed - right now, we are changing the return types but in reality we could be mistaken because nothing brakes if it's wrong in a phpDoc.

**Comment by mrcnpdlk** [comment]
Your solution for transaction doesn't work for nested transactions.
You restored my changes. 😢  For each nested transaction we have to check if it is in another transaction - for methods: beginTransaction() and both commit() and rollback();

See my example pseudo code: https://github.com/skipperbent/pecee-pixie/pull/25

Now, my code throw exception:
```
PHP Fatal error:  Uncaught PDOException: There is no active transaction in ...\src\Pecee\Pixie\QueryBuilder\QueryBuilderHandler.php:1197
```

**Comment by skipperbent** [comment]
@mrcnpdlk Haha 😈 😄 Tried some different approaches - i was about to give up and go to bed last night - then i stored the work in a local branch, made a git reset and began over 😫 but I got a feeling that I'm on the right track - think I've solved the nested-transaction issue with my latest fix. The psuedo examples you've posted works now.

**Comment by mrcnpdlk** [comment]
I know I am annoying, but unfortunately still doesn't work...
I am throwing exception in `secondTrans()` function. Of course, Exception is correct now
```
Column not found: 1054 Unknown column 'fruit' in 'field list'
```
but transaction wasn't rollbacked. First function (`firstTrans()`) add item to database but it shouldn't.

You have to check (and save state in some variable, for example `inT`) being in transaction BEFORE next nested transaction, not during.
See https://github.com/skipperbent/pecee-pixie/pull/25/commits/10a2558836bbc55f96b8346daf9d1ed81b86ec6a?diff=unified#diff-19f3df010f7a0d8dfb53233389517919R1208

Next, we have to use this variable to judge if we need to open new transaction, commit or in case of exception rollback. Only if `inT===false` we can fire those three methods.

**Comment by skipperbent** [comment]
Sorry I didn't notice your reply earlier.

> It is good thought but hard to accomplish.
> Do you have any idea how to do this?
> Fist of all, the solution have to be user friendly.
> We can do this, using different methods depended of arguments, for example:
> 
> where(string),
> whereRaw(raw),
> whereClosure(closure)
> Disadvantages - many many methods and code duplicates.
> Second, as you said is common Adapter but a think that obfuscate the code and using library will be harder.

The functionality will remain the same - it would have no effect on how the library is used. It would only be used to simplify the way queries are handled internally within the library (Raw, Closure etc).

Maybe the existing `QueryObject` class could be extended a little to contain some of the `mixed` type of queries. So for instance, if you call `$qb->raw(...)` a `RawQueryObject` would just be used instead of the `Raw` class- with the same methods as the `Raw` class, but inherited from a common `QueryObject`. That way the library can always guarantee what types each method will return.

I understand if it sounds confusing, but trust me it's gonna be good and it won't change the user experience or make the project unnecessarily complicated 😄

**Comment by skipperbent** [comment]
> I know I am annoying, but unfortunately still doesn't work...
> I am throwing exception in secondTrans() function. Of course, Exception is correct now
> 
> Column not found: 1054 Unknown column 'fruit' in 'field list'
> but transaction wasn't rollbacked. First function (firstTrans()) add item to database but it shouldn't.
> 
> You have to check (and save state in some variable, for example inT) being in transaction BEFORE next nested transaction, not during.
> See 10a2558?diff=unified#diff-19f3df010f7a0d8dfb53233389517919R1208
> 
> Next, we have to use this variable to judge if we need to open new transaction, commit or in case of exception rollback. Only if inT===false we can fire those three methods.

Fuck you're right, the rollback doesn't work as expected.. damn 😪 but I got a good feeling about this, I'm pretty sure I can get this working by merging some of the work you've done in the `v4-development` branch that keeps track of the state 👍 We're almost there!

**Comment by skipperbent** [comment]
@mrcnpdlk 

I'm trying to recreate the rollback issue, however it works fine here. Both `people` and `animal` table has 0 items. Can you show an example on how it fails with yours?

```php
public function testNestedTransactionsRollback()
{

	$this->builder->statement('TRUNCATE `people`; TRUNCATE `animal`');

	try {

		$this->builder->transaction(function (Transaction $qb) {

			$qb->transaction(function (Transaction $qb) {

				$qb->table('people')->insert(
				[
					'name'     => 'Henry',
					'age'      => '56',
					'awesome'  => '1',
					'nickname' => 'ponylover95',
				]);

			});

			$qb->transaction(function (Transaction $qb) {

				throw new Exception();

			});

		});

	} catch(Exception $e) {
            // Don't break the unit test...
	}


	$animalsCount = $this->builder->table('animal')->count();
	$personsCount = $this->builder->table('people')->count();

	$this->assertEquals($animalsCount, 0);
	$this->assertEquals($personsCount, 0);
}
```

**Comment by mrcnpdlk** [comment]
**Edited: Shame on me... In by test database i used unfortunately MyISAM engine.** 
After change your example works (Case 1), Case 2 and 3 still doesnt work - i'am using global queryBuilderHandler instead of Transaction handler.

### Case 1
I have checked twice on your v4-optimisation branch.
Function `secondTrans()` throw Exception - column `name2` doesn't exist.
Still `foo` is added

```php
$oQuery = (new \Pecee\Pixie\Connection('mysql', $config))->getQueryBuilder();

$oQuery->transaction(function (\Pecee\Pixie\QueryBuilder\Transaction $qb) {
    firstTrans($qb);
    secondTrans($qb);
});

function firstTrans(\Pecee\Pixie\QueryBuilder\QueryBuilderHandler $oQuery)
{
    $oQuery->transaction(function (\Pecee\Pixie\QueryBuilder\Transaction $qb) {
        $qb->table('table_one')->insert(['name' => 'foo']);
    });
}

function secondTrans(\Pecee\Pixie\QueryBuilder\QueryBuilderHandler $oQuery)
{
    $oQuery->transaction(function (\Pecee\Pixie\QueryBuilder\Transaction $qb) {
        $qb->table('table_one')->insert(['name2' => 'bar']);
    });
}
```

I get `Column not found: 1054 Unknown column 'name2' in 'field list'` but `foo` is added.

### Case 2

Next Example, from my life. I am using QueryBuilderHandler as a property of main project singleton class. I can get access to handler from everywhere by calling `App::getInstance()->pixieConn`. So above example should be a bit modificated (not `$qb` but global `$oQuery` argument):
```php
$oQuery->transaction(function (\Pecee\Pixie\QueryBuilder\Transaction $qb) use($oQuery) {
    firstTrans($oQuery);
    secondTrans($oQuery);
});

function firstTrans(\Pecee\Pixie\QueryBuilder\QueryBuilderHandler $oQuery)
{
    $oQuery->transaction(function (\Pecee\Pixie\QueryBuilder\Transaction $qb) {
        $qb->table('table_one')->insert(['name' => 'foo']);
    });
}

function secondTrans(\Pecee\Pixie\QueryBuilder\QueryBuilderHandler $oQuery)
{
    $oQuery->transaction(function (\Pecee\Pixie\QueryBuilder\Transaction $qb) {
        $qb->table('table_one')->insert(['name2' => 'bar']);
    });
}
```

Still `Column not found: 1054 Unknown column 'name2' in 'field list'`

### Case 3

And next one example with global `$oQuery` usage. In this time first and second function not generate the Exception. `foo` and `bar` is added to database but... but Exception is thrown `There is no active transaction in ...\QueryBuilder\QueryBuilderHandler.php:1213`
```php
$oQuery = (new \Pecee\Pixie\Connection('mysql', $config))->getQueryBuilder();

$oQuery->transaction(function (\Pecee\Pixie\QueryBuilder\Transaction $qb) use($oQuery) {
    firstTrans($oQuery);
    secondTrans($oQuery);
});

function firstTrans(\Pecee\Pixie\QueryBuilder\QueryBuilderHandler $oQuery)
{
    $oQuery->transaction(function (\Pecee\Pixie\QueryBuilder\Transaction $qb) {
        $qb->table('table_one')->insert(['name' => 'foo']);
    });
}

function secondTrans(\Pecee\Pixie\QueryBuilder\QueryBuilderHandler $oQuery)
{
    $oQuery->transaction(function (\Pecee\Pixie\QueryBuilder\Transaction $qb) {
        $qb->table('table_one')->insert(['name' => 'bar']);
    });
}
```

**Comment by mrcnpdlk** [comment]
Look at #38

**Comment by skipperbent** [comment]
@mrcnpdlk 

You can't pass the `QueryBuilderHandler` instance, you need to use the Transaction instance provided by the first call to `transaction()`, otherwise it will create a new transaction which might not work as expected.

**Comment by skipperbent** [comment]
This is the proper way to use it. Notice the `Transaction` object are passed instead of using the `QueryBuilderHandler`.

```php
$oQuery->transaction(function (\Pecee\Pixie\QueryBuilder\Transaction $qb) {
    firstTrans($qb);
    secondTrans($qb);
});

function firstTrans(\Pecee\Pixie\QueryBuilder\Transaction $oQuery)
{
    $oQuery->transaction(function (\Pecee\Pixie\QueryBuilder\Transaction $qb) {
        $qb->table('table_one')->insert(['name' => 'foo']);
    });
}

function secondTrans(\Pecee\Pixie\QueryBuilder\Transaction $oQuery)
{
    $oQuery->transaction(function (\Pecee\Pixie\QueryBuilder\Transaction $qb) {
        $qb->table('table_one')->insert(['name2' => 'bar']);
    });
}
```

**Comment by mrcnpdlk** [comment]
> You can't pass the QueryBuilderHandler instance, you need to use the Transaction instance provided by the first call to transaction(), otherwise it will create a new transaction which might not work as expected.

What when I dont able to transfer Transaction object between transactions?

**Comment by skipperbent** [comment]
You do that in both case 2 and 3. That might explain why rollback ain't working.

**Comment by mrcnpdlk** [comment]
I this example yes, but im my real world i cannot because like I said: 

>  I am using QueryBuilderHandler as a property of main project singleton class. I can get access to handler from everywhere by calling App::getInstance()->pixieConn.

**Comment by skipperbent** [comment]
You should store the connection instead as the querybuilder are storing statements each time you're using it.

Anyways it's not an error if it's not rolling back when you're using the querybuilder instead of transaction object while inside a transaction.

**Comment by mrcnpdlk** [comment]
OK, how to resolve this case (pseudocode)?
Functions `foo()`, `bar()`,`baz()`allInOne(), have no argument.
```php
function foo(){
    $qb->transaction(function(Transaction $t){
        [...]
    });
}

function bar(){
    $qb->transaction(function(Transaction $t){
        [...]
    });
}

function baz(){
    $qb->transaction(function(Transaction $t){
        [...]
        bar();
    });

}

function allInOne(){
    $qb->transaction(function(Transaction $t){
        foo();
        bar();
    });
}
```

**Comment by skipperbent** [comment]
You can't - if you are doing something like that, then you are doing it wrong as it is creating 4 independent transactions.

**Comment by skipperbent** [comment]
It's created like that by design. The whole idea of separating the transactions from the QueryBuilder and keeping it "maintained" is that it allows you to control what you want be in your transaction. If it were in the querybuilder, everything will be rolled back.

For instance:  Let's say you want to save a user, but each time you are storing something to a log. Then you can control which part is rolled back.

The example below will rollback user on error - while keeping the log. If the transaction were on the `QueryBuilderHandler` everything would be rolled back.

```php
$this->qb->transaction(function (Transaction $transaction) {

	$name = $this->user->name;
	$gender = $this->user->gender;

	$this->qb->update([
		'log' => 'Saving user ' . $name
	]);
	
	$transaction->save([
		'name' => $name,
		'gender' => $gender,
	]);

});
```

**Comment by mrcnpdlk** [comment]
In this case, if you use DB as log handler or something like that,  you have a little right - we have to separate handlers: for transaction and non-transaction mode.

> You can't - if you are doing something like that, then you are doing it wrong as it is creating 3 independent transactions.

I disagree it is wrong. It allow you to keep database clear. 

> You should store the connection instead as the querybuilder are storing statements each time you're using it.

Yes, you have right - I have corrected my code. On the other hand calling method `table()` creates new instance of QB inside.

**Comment by skipperbent** [comment]
> In this case, if you use DB as log handler or something like that, you have a little right - we have to separate handlers: for transaction and non-transaction mode.

The log-handler was just an example - it could be something completely different it all depends on what you are trying to achieve. 

> I disagree it is wrong. It allow you to keep database clear.

The database should only be clear when you specifically want it to be clear. You don't want nothing to be inserted just because one query fail - but rather have the option to specify which one.

> On the other hand calling method table() create new instance of QB inside.
You're right - that's true, my bad.
