### ISSUE TITLE
Translate PDOExcteption to user-friendly Exception

### ISSUE THREAD

**Issue by mrcnpdlk** [skipperbent/pecee-pixie#33]
In my production project I map Mysql PDOExceptions to user-friendly Exceptions, i.e
```php
if ($e instanceof \PDOException) {
            if ($e->errorInfo[0] === '23000') {
                switch ($e->errorInfo[1]) {
                    case 1036:
                        return new Exception\ReadOnly($e->errorInfo[2], 1, $e); //Message: Table '%s' is read only
                    case 1044:
                        return new Exception\DbAccessDenied($e->errorInfo[2], 1, $e); //Message: Access denied for user '%s'@'%s' to database '%s'
                    case 1045:
                        return new Exception\AccessDenied($e->errorInfo[2], 1, $e); //Message: Access denied for user '%s'@'%s' (using password: %s)
                    case 1060:
...
```

I can also do something like this for Sqlite and Pgsql.
Do you think, that it would be useful?

**Comment by skipperbent** [comment]
I think it's a really nice feature - In my opinion, everything that can help the developer to more easily understand a problem and thereby fix it, is much appreciated.

**Comment by skipperbent** [comment]
This issue is marked as a feature, as it should most definitely be included in the library.

**Comment by skipperbent** [comment]
The feature is now available in version 4.5.0:
https://github.com/skipperbent/pecee-pixie/releases/tag/4.5.0

wuup wuup 😄 👍

**Comment by mrcnpdlk** [comment]
I've checked. Everything works as expected. You can close issue.

**Comment by skipperbent** [comment]
Great! I might try to create some unit tests for other SQL servers than mysql so we can be 100% sure.

Great work 😀
