### ISSUE TITLE
Share Idea folder in Git

### ISSUE THREAD

**Issue by mrcnpdlk** [skipperbent/pecee-pixie#36]
Do You have something against to share .idea folder in git repository?

https://intellij-support.jetbrains.com/hc/en-us/articles/206544839-How-to-manage-projects-under-Version-Control-Systems

**Comment by skipperbent** [comment]
No no, not at all - I just had some issues getting php-units to run until i trashed the .idea folder, so I thought that i would spare you and others the same pain by me overwriting something.

If you prefer the .idea folder to be present, you should do that. For me it's no problem either way 😄

**Comment by mrcnpdlk** [comment]
Thanks.
In the nearest PR I gonna change main .gitignore file and I will be grateful if you merge it.

**Comment by skipperbent** [comment]
The `v4-development` already contain you latest changes, including the `.gitignore` file. It's only in my `v4-optimizations` branch (which are work-in-progress) that those are gone but i'll revert those - so unless you've changed something it won't be necessary with a PR.
