### ISSUE TITLE
Get query from insert and update queries

### ISSUE THREAD

**Issue by pieterh83** [skipperbent/pecee-pixie#44]
Is it possible to get the query that is executed for an input and update query?

**Comment by skipperbent** [comment]
Hi @pieterh83.

Unfortunately it's only possible to get the query by adding an event-handler at the moment. However I've been annoyed by this myself - so in the next release this feature will definitely be included.

I'll keep you posted when the next release is ready, until then i suggest you add an eventhandler to analyze your queries.

/ Simon

**Comment by skipperbent** [comment]
Hi @pieterh83 .

In version 3.5.2 and version 4.1.3 I've added the option to get the `QueryObject` for the last executed query. So finally you'll be able to easily debug the queries executed.

You retrieve the last executed query-string by calling:

```php
$qb->getLastQuery()->getRawSql();
```

The QueryObject is explained in details in the documentation:
https://github.com/skipperbent/pecee-pixie#get-built-query

Thanks for taking your time to report the issue, I appreciate your feedback.

If you have any further questions or ideas, feel free to create another ticket.

/ Simon
