### ISSUE TITLE
Join on a subquery

### ISSUE THREAD

**Issue by allejo** [skipperbent/pecee-pixie#61]
Would it be possible to add support for joining on subqueries? e.g. build a query like so:

```sql
SELECT * 
FROM table1 alias1 
   INNER JOIN (SELECT id 
               FROM   table2 
               WHERE  field = 1) alias2 
           ON alias2.id = alias1.id 
```

The original Pixie doesn't support but I'd hope to see this feature. See https://github.com/usmanhalalit/pixie/issues/52

**Comment by skipperbent** [comment]
We've added many of our features as pull requests on the original project, but the author doesn't seem to have either the time or will to implement new features it seems :( 

**It should be possible to achieve a query like your example, by doing something like this:**

```php
$subQuery = $qb->table('table2')->select(['id'])->where('field', '=', '1');

$query = $qb->table('table1')->alias('alias1')->join($qb->subQuery($subQuery, 'alias2'), 'alias2.id', '=', 'alias1.id');
```

**It should a query similar to the one in your example:**

```sql
SELECT * FROM `table1` AS `alias1` INNER JOIN (SELECT `id` FROM `table2` WHERE `field` = '1') AS `alias2` ON `alias2`.`id` = `alias1`.`id`
```

/ Simon

**Comment by allejo** [comment]
Ah hah! That did the trick in both the original library (minus alias support) and this project! Thank you very much!

**Comment by skipperbent** [comment]
@allejo Great - I'm happy you got it working! I know the feeling of being stuck, especially when dealing with complex queries.

If you have any further questions, comments or experiencing issues of any kind- feel free to create another ticket.

/ Simon
