### ISSUE TITLE
Using count() on statement included groupBy()

### ISSUE THREAD

**Issue by mrcnpdlk** [skipperbent/pecee-pixie#75]
Calling statement `->table('foo_table')->groupBy('bar')->count()` is returning unsuitable response.
That is because Pixie is translating query into:
`select count(*) as field from foo_table group by bar`.
In this case (only if groupBy() exists) we have to use subquery: 
`select count(*) as field from (select * from  foo_table group by bar) as some_alias_table`.
Unfortunately selecting by wildcard (*) is much slower but answer is correct. 

In my opinion `agregate()` method should be fixed.
If I am right give me feedback, maybe I will find some time to patch this.

**Comment by skipperbent** [comment]
Hey @mrcnpdlk

Hmm.. While I totally see your point - I think changing it might break the existing code for people using the library and might cause issues in situations where one is really needing the groupBy without a sub-query -
so I think we might introduce other errors if we change that behavior, as using it like the examples below makes sense:

```php
$qb->groupBy('orders')->skip(5)->take(1)->count();
```
Or something like this:

```php
$postsQuery = $qb->select('id')->groupBy('parent_id');

$qb->whereIn('id', $qb->subQuery($postsQuery))->get();
```

However another thing I was thinking about was maybe not requiring users to use the `subQuery` method, but instead allowing users to just pass `QueryBuilderHandler` objects. It would make the code a lot cleaner:

```php
$postsQuery = $qb->select('id')->groupBy('parent_id');

$qb->whereIn('id', $postsQuery)->get();
```

Let me know what you think. 

Ps: sorry if the examples are all weird, I'm writing this from my phone which makes it difficult to write php 😀

/ simon

**Comment by mrcnpdlk** [comment]
In my opinion this is the bug. I am gonna try to explain that in this use case. I am using it for generatong query for pagination. I need total count  value to display it on page.

For example, we have table `some_table`:

| ID   | FRUIT  |
| ---- | ------ |
| 1    | apple  |
| 2    | cherry |
| 3    | cherry |
| 4    | cherry |

Now, we want to know how many row is for any fruit:

```php
$tRows = $q
    ->table('some_table')
    ->select('name')
    ->select(q->raw(count(*) as `how_many_rows`))
    ->groupBy('name')
    ->get();
```

Response:

| FRUIT  | HOW_MANY_ROWS |
| ------ | ------------- |
| apple  | 1             |
| cherry | 3             |

The next one, we want to know how many rows is in the table above. Of course we can use native php function `count()` on obtained earlier `tRows` variable, but NO, i want to use Pixie method `count()` - it is faster, better, easier, more universal.

We expect (i expect) that below statement returns `2`, but NO, it returns `1` :sob: (or `3`, depends on sorting direction).

```php
$counter = $q
    ->table('some_table')
    ->select('name')
    ->select(q->raw(count(*) as `how_many_rows`))
    ->groupBy('name')
    ->count();
echo $counter; // 1

// RAW QUERY
// 'select name, count(*) as how_many_rows, count(*) as field from some_table group by name'
```



PS:

What do You mean using `skip()` & `take()`?
Maybe we can include some parameter for `count()` method? For example `count(bool &forAll = false)`

**Comment by mrcnpdlk** [comment]
For my usage I override `count()` method:
```php
/**
     * @return int
     * @throws \Pecee\Pixie\Exception
     */
    public function count() : int
    {
        if (empty($this->statements['groupBys'])) {
            return parent::count();
        }

        return \count($this->get());
    }
```

**Comment by skipperbent** [comment]
@mrcnpdlk Haha, I know it sucks in your specific case - but I promise you it's not a bug - otherwise MySQL would have returned a beautiful newly-created custom exception 😄 

The `count` method just adds a count to whatever query you are creating, so it's perfectly fine.

In regards to the skip and take, it was just to point out a specific use-case. Your hack will make you unable to create a query like this:

```php
$qb
   ->table('posts')
   ->groupBy('comments')
   ->orderBy($qb->raw('COUNT(`id`)'))
   ->skip(5)
   ->limit(1)
   ->count();
```

```sql
# take the view count for the fifth result
SELECT COUNT(`id`) AS `field` FROM `post` GROUP BY `views` ORDER BY COUNT(`id`) DESC LIMIT 1,5
```

Try to change you query to use `SUM` instead of `COUNT`. I think that's the behavior you are looking for:
```sql
select name, SUM(*) as how_many_rows, count(*) as field from some_table group by name
```

I have some ideas though:

Maybe we could make `count` behave like other methods in the `QueryBuilderHandler` by adding some optional parameters to the method, for example:
1. method takes argument for which fields to count 
2. **OR** a `Raw` / `\Closure` object

And then for easy of use, we could create a `countAll` method which counts all the rows like

Then you can always get a count on the entire query by calling `$qb->count($myQuery)`.

/ Simon

**Comment by skipperbent** [comment]
Seems like the `count` has never really been working properly. Because it removes any `orderBy`, `limit` or `offset`. So i guess you're right, it was supposed to count the entirety of the query.

**Comment by skipperbent** [comment]
@mrcnpdlk The `count` method really was fucked - so you were totally right. It excluded some statements like order and limit - so the count wasn't even accurate. I looked in the original pixie and it seems like it has the same weird behavior.

Anyway I've fixed it like you suggested and added some more aggregate methods like `sum`, `average`, `min` and `max`. 😃 

Enjoy my man and thanks for the suggestion! ^^

**Comment by skipperbent** [comment]
The fix is available in version 4.6.0:

https://github.com/skipperbent/pecee-pixie/releases/tag/4.6.0

**Comment by mrcnpdlk** [comment]
Is good to require so high version of php (7.2) in last release? 🤕 
Now, i'am thinking, you reject a large part of the community that uses Pixie...

**Comment by skipperbent** [comment]
@mrcnpdlk Sorry for the late response, the github notification got lost somewhere in cyperspace.. 

You're right - I downgraded to version 7.1, hope you can live with that. :)

/ Simon

**Comment by mrcnpdlk** [comment]
@skipperbent Thanks a lot. I'am thinking about upgrade PHP to 7.2 on my production server. In the near future I will come back 😃 
You can close this issue.

**Comment by skipperbent** [comment]
Version 4.7.0 and above uses php 7.1 - the upgrade process from version 7.0 should be pretty seamlessly.

Thanks for all your feedback :)
