### ISSUE TITLE
Call to undefined method Pecee\Pixie\Connection::table()

### ISSUE THREAD

**Issue by zaingithub** [skipperbent/pecee-pixie#8]
$qb = new \Pecee\Pixie\Connection('sqlite', [
                'driver'   => 'sqlite',
			    'database' => storage_path('tesdb.sqlite'),
			    'prefix'   => '',
		    ]);	
			
		print_r( $row = $qb->table('users')->find(3) );

**Comment by skipperbent** [comment]
You have to call `getQueryBuilder` in order to do that. I'm sorry that the documentation is not clear on that.

**Comment by zaingithub** [comment]
Thanks! :)
