### ISSUE TITLE
Suggestion - Support for MySQL's JOIN ... USING statement

### ISSUE THREAD

**Issue by Fishy49** [skipperbent/pecee-pixie#85]
I modified the original pixie library to support using the MySQL USING statement in the join. This will join two tables on a column that shares the same name between the two tables.

`SELECT * FROM table1 INNER JOIN table2 USING(common_column_name)`

The benefit of this is that you don't have to qualify table names in your WHERE statements.

I use this extensively as my applications generate very large dynamic queries with many many different tables that are often filtered with WHERE statements.

Usage in my version is like this:
`$db->table('table1')->join('table1', 'table2', 'using', 'common_column_name')`

My modifications were a bit hackey and only focused on MySQL so I am unsure if it was done "properly" or broke anything else.

I would love to put his in as a feature suggestion to this version of pixie as it seems much more robust.

**Comment by skipperbent** [comment]
Hi @Fishy49 .

Thanks for taking the time to suggest a new feature- I really appreciate all the feedback I can get.

Great idea! I haven't really used the `JOIN USING` syntax to be honest - however it does make sense, especially when dealing with complex queries with many relations to each other I could imagine. 👍 

Anyways, I've added the feature you requested and it should be available in the next upcoming release.

To keep it simple and avoid any confusion, I've created a separate method called `joinUsing($table, array $columns, $joinType = '')`. There will be more info in the documentation once the release it ready.

I'll keep you posted - thanks again!

Peas out!

/ Simon

**Comment by skipperbent** [comment]
The feature is available in version 4.9.0:
https://github.com/skipperbent/pecee-pixie/releases/tag/4.9.0

More info on how to use the `JOIN USING` syntax here:
https://github.com/skipperbent/pecee-pixie#join-using-syntax

/ Simon

**Comment by Fishy49** [comment]
Wow! Thanks for such a quick turnaround! Can't wait to test it out!

**Comment by skipperbent** [comment]
@Fishy49 

No problem, you're welcome! Let me know if you experience any issues, and feel free to comment if you have any questions etc. :) 

/ Simon
