### ISSUE TITLE
count() return unsuitable type

### ISSUE THREAD

**Issue by mrcnpdlk** [skipperbent/pecee-pixie#91]
Doc says that `count()` method returns float type.
But `0` is an integer. Should be `0.0`.
[see here](https://github.com/skipperbent/pecee-pixie/blob/4.8.0/src/Pecee/Pixie/QueryBuilder/QueryBuilderHandler.php#L245 )

On the other hand, before version 4.6.0 `count()` method was returning `integer`. It was better than float, because in many places i use comparison like that:
```$query->count() === 0```
After 4.6.0 it always returns `false` 🤕  - types are different.

**Comment by skipperbent** [comment]
Hi @mrcnpdlk .

Not sure why it has been changed from `integer` to `float`, that's weird- can't find the exact return type for MySQL, but as far as I can see MS-SQL always returns `integer` as the datatype:
https://docs.microsoft.com/en-us/sql/t-sql/functions/count-transact-sql?view=sql-server-2017

I'll make sure the PR will be added to the next release 👍 

/ Simon

**Comment by mrcnpdlk** [comment]
Fixed.
