### ISSUE TITLE
support for TravisCI + code coverage

### ISSUE THREAD

**Issue by mrcnpdlk** [skipperbent/pecee-pixie#96]
I've integrated project with [TravisCI](https://travis-ci.org) and [https://coveralls.io](https://coveralls.io).
Code coverage report is generated only if unit tests return success, so we need fix some bugs in tests. One of them, see: https://github.com/skipperbent/pecee-pixie/pull/94/commits/a4095d9a0ac368806e15ce9a4b9d311989c7f3e9 in https://github.com/skipperbent/pecee-pixie/pull/94

I've also added mysql support for travisCI integration.
https://coveralls.io/github/mrcnpdlk/pecee-pixie
https://travis-ci.org/mrcnpdlk/pecee-pixie

**Comment by skipperbent** [comment]
Nice work, your implementation will be added in the next release 👍 

/ Simon

**Comment by skipperbent** [comment]
Added in version 4.10.0
